### ISSUE TITLE
Not SilverStripe 4 Compatible

### ISSUE THREAD

**Issue by purplespider** [burnbright/silverstripe-externalurlfield#16]
Doesn't look like the code has been updated for SS4?

_Warning: Declaration of BurnBright\ExternalURLField\ExternalURLField::setValue($url) should be compatible with SilverStripe\Forms\FormField::setValue($value, $data = NULL) in externalurlfield/src/ExternalURLField.php on line 12_

**Comment by robbieaverill** [comment]
This has been fixed in #17
